config/routes.rb
HappyBottle::Application.routes.draw do
  root to: 'welcome#index'
  resources :users, only: [:new, :create, :update] do
    member do
      get '/verify/:invitation_token' => :verify, as: :verify
      get :setting
    end
  end
  resources :bottles, only: [:new, :create]
  resources :session, only: [:new, :create]
  get 'bottles/tag' => 'bottles#tag'

  

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
  belongs_to :owner, class_name: "User"

  validates :message, presence: true

  scope :delivered , -> { where('delivered_at IS NOT NULL') }
  scope :not_delivered_yet , -> { where('delivered_at IS NULL') }
  scope :time_has_passed , -> { where('created_at <= ?', 1.month.ago) }

  class << self
    def analize_words
      words = Hash.new(0)

      all.each do |bottle|
        # 絵文字を除去
        tag = TAGGER.parse(bottle.message.encode('cp932', invalid: :replace, undef: :replace, replace: '').encode('UTF-8'))

        tag.each do |node|
          feature = node.feature

          # XXX Bad code...
          if feature['名詞']
            words[node.surface] += 1
          end
        end
      end

      data = []
      words.each do |word, weight|
        data << {word: word, weight: weight}
      end
      data
    end

    def find_by_tag(tag)
      where(["message LIKE ?", "%#{tag}%"])
    end
  end

  def deliver!(date = DateTime.now)
    self.delivered_at = date
    save!
  end
end

app/models/partnership.rb
class Partnership < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  belongs_to :partnership
  has_many :bottles, foreign_key: 'owner_id', dependent: :destroy

  validates :email, presence: true, uniqueness: true

  before_save do
    self.hashed_password = self.class.create_hash(self.password) if self.password.present?
  end

  class << self
    def find_by_email_and_password(email, password)
      User.where(email: email, hashed_password: create_hash(password)).first
    end

    def create_hash(password)
      Digest::SHA1.hexdigest(password)
    end
  end

  def activated?
    self.hashed_password.present? && self.invitation_token.blank?
  end

  def partner
    # TODO Refactor
    (self.partnership.users - [self]).first
  end

  def create_bottle(params)
    Bottle.create!(params) do |bottle|
      bottle.owner = self
    end
  end

  def update_invitation_token
    self.invitation_token = OpenSSL::Random.random_bytes(16).unpack("H*").first
  end

  def verify!
    self.invitation_token = nil
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def store_user(user)
    session[:user_id] = user.id
  end

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = User.find_by_id(session[:user_id])
  end

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :login_required
  before_action :activated_required

  def new
    @bottle = Bottle.new
    @partner = current_user.partner
    @key_words = current_user.partner.bottles.delivered.analize_words
  end

  def create
    begin
      @bottle = current_user.create_bottle(bottle_params)
    rescue
      redirect_to new_bottle_path, alert: 'メッセージが入力されていません！'
      return
    end

    redirect_to new_bottle_path, notice: '幸せが詰まった瓶を流しました！'
  end

  def tag
    @bottles = current_user.partner.bottles.delivered.find_by_tag(URI.decode(params[:tag])).order('created_at DESC')
  end

  private

  def bottle_params
    params.require(:bottle).permit(:message)
  end

  def activated_required
    redirect_to setting_user_path(current_user) unless current_user.activated?
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email_and_password(params[:user][:email], params[:user][:password])

    if @user
      store_user @user

      redirect_to new_bottle_path
    else
      redirect_to new_session_path, alert: 'emailまたはパスワードが一致しません'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    begin
      User.transaction do
        @user = User.new(user_params)
        @user.save!
        partnership = Partnership.create!
        @user.partnership = partnership
        @user.save!

        partner = User.create!(email: params[:invitation])
        partner.partnership = partnership
        partner.update_invitation_token
        partner.save!

        InvitationMailer.invite(partner, @user).deliver
      end

      store_user @user

      redirect_to new_bottle_path, notice: "#{params[:invitation]} 宛に招待メールを送信しました!"
    rescue => e
      self.logger.error ["#{e.class} #{e.message}:", *e.backtrace.map {|m| '  '+m }].join("\n")

      redirect_to new_user_path, alert: 'Email はすでに登録されています' # XXX 他にもありそう
    end
  end

  def update
    @user = User.find(params[:id])

    @user.update_attributes!(user_params)

    redirect_to new_bottle_path
  end

  def verify
    @user = User.find_by_invitation_token(params[:invitation_token])
    @user.verify!

    store_user @user

    redirect_to setting_user_path(@user)
  end

  def setting
    # TODO password が nil だと、必ず setting に飛ばすようにしたい
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :reject_if_login

  def index
  end

  private

  def reject_if_login
    redirect_to new_bottle_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/bottles/new.html.haml
%div.container-fluid
  %div.row-fluid
    %center
      =image_tag "bottle.jpg", width: "500px"
      = form_for @bottle, url: bottles_path do |f|
        %div
          = f.text_area :message, placeholder: "どんな幸せがありましたか?"

        = f.submit "#{@partner.name.presence || @partner.email}さんへ瓶を流す", class: "btn btn-primary  btn-large"

      %span.tag-title
        あなたに届いた瓶のかけら
      %div#peace_of_bottle{ style: "width: 100%; height: 200px;"}

    :javascript
      var word_array = #{
          @key_words.map {|key_word|
            {text: key_word[:word] , weight: key_word[:weight], link: bottles_tag_path(tag: key_word[:word]) }
          }.to_json
        };

      $(function() {
        $("#peace_of_bottle").jQCloud(word_array);
      });

app/views/bottles/tag.html.haml
%div.container-fluid
  %div.row-fluid

    %ul.buttle-list
      - @bottles.each do |bottle|
        %li.well
          %span.message= bottle.message
          %span.created-at= bottle.created_at.strftime("%Y-%m-%d %H:%M")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HappyBottle
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="viewport" content="width=device-width initial-scale=1.0 user-scalable=no")
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      .navbar.navbar-fixed-top
        .navbar-inner
          .container-fluid
            %a.brand(href='/') HappyBottle

    - {notice: 'success', alert: 'error'}.each do |key, name|
      - if flash[key]
        .alert{class: "alert-#{name}"}
          = flash[key]

    .content-wrapper
      = yield

    %footer.footer
      .container
        %p
          %i © 2013 HappyBottle. All rights reserved.

app/views/session/login.html.haml
%div.container
  %div.row

    = form_for @user, url: session_path do |f|
      %div
        = f.label :email
        = f.text_field :email

      %div
        = f.label :password
        = f.text_field :password

      = f.submit 'OK', class: "btn"

app/views/session/new.html.haml
%div.container-fluid
  %div.row-fluid
    = form_for @user, url: '/session' do |f|
      %div
        = f.label :email
        = f.text_field :email, required: true

      %div
        = f.label :password
        = f.password_field :password, required: true

      = f.submit 'OK', class: "btn"

    = link_to 'Sign Up', new_user_path

app/views/users/new.html.haml
%div.container-fluid
  %div.row-fluid

    = form_for @user, url: users_path do |f|
      %div
        = f.label :name
        = f.text_field :name, required: true

      %div
        = f.label :email
        = f.text_field :email, required: true

      %div
        = f.label :password
        = f.password_field :password, required: true

      %div
        = f.label :invitation_email
        = text_field_tag :invitation, nil, placeholder: 'your.partner@exmpale.com', required: true

      = f.submit 'OK', class: "btn"

    = link_to 'Sign In', new_session_path

app/views/users/setting.html.haml
%div.container-fluid
  %div.row-fluid
    = form_for @user do |f|
      %div
        = f.label :name
        = f.text_field :name, required: true

      %div
        = f.label :email
        = f.text_field :email, disabled: true

      %div
        = f.label :password
        = f.password_field :password, required: true

      = f.submit 'OK', class: "btn"

app/views/welcome/index.html.haml
.jumbotron.masthead
  .container
    .hero-unit
      %h1 Happy Bottle

      %p.title-detail
        ちょっとした幸せを小瓶に詰めて、あなたのパートナーにお届けします。

      %p
        = link_to 'Sign In', new_session_path, class: 'btn btn-primary btn-large'

.container
  .row-fluid
    .span4
      %h2
        こんな人向け
      %p
        長年一緒に過ごしてきたパートナーと、もっと幸せを共有したいあなたへ贈ります。

    .span4
      %h2
        シチュエーション
      %p
        毎日、少しでも幸せだったことをそっと瓶につめておきましょう。
        その気持ちは忘れかけた頃に、あなたのパートナーへメールで届くはずです。

    .span4
      %h2
        嬉しいこと
      %p
        ほんの少しの幸せやちょっとした嬉しさを、あなたのパートナーにもおすそわけしませんか？
        目の前では照れくさくて相手に伝えづらい日々の感謝の気持ちを伝えてみませんか？
        そんなあなたの素直な気持ちを、Happy Bottle があなたに代わってこっそりお届けします。